import GeneralView from "@/components/layout/GeneralView";
import "./App.scss";

function App() {
	return (
		<GeneralView>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
			<p>This is Sample text for auto generated</p>
		</GeneralView>
	);
}

export default App;
